config/routes.rb
Rails.application.routes.draw do
  resources :questions do
    resources :answers
  end
  resources :lessons

  root to: 'lessons#index'
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question

  validates :text, presence: true, length: {in: 1..50}
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  has_many :images, class_name: LessonImage, dependent: :destroy
  has_many :questions, dependent: :destroy

  accepts_nested_attributes_for :images, allow_destroy: true,
    reject_if: :all_blank

  validates :name, presence: true, length: {in: 5..30}
  validates :description, presence: true, length: {in: 30..6000}
end

app/models/lesson_image.rb
class LessonImage < ActiveRecord::Base
  belongs_to :lesson

  has_attached_file :file,
    styles: { medium: "300x300>", thumb: "100x100>", mini: "24x24>" },
    path: ":rails_root/public/uploads/:class/:id/:basename_:style.:extension",
    url: "/uploads/:class/:id/:basename_:style.:extension",
    default_url: "/images/placeholders/:style/missing.png"
  validates_attachment :file,
    content_type: { content_type: /\Aimage\/.*\Z/ },
    file_name: { matches: [/png\Z/, /jpe?g\Z/] },
    size: { in: 0..2.megabytes }
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :lesson
  has_many :answers, dependent: :destroy

  accepts_nested_attributes_for :answers, allow_destroy: true,
    reject_if: :all_blank

  validates :text, presence: true, length: {in: 5..50}
end

app/controllers/answers_controller.rb
class answersController < ApplicationController
  before_action :set_answer, only: [:show, :edit, :update, :destroy]

  # GET /answers
  def index
    @answers = Answer.all
  end

  # GET /answers/1
  def show
  end

  # GET /answers/new
  def new
    @answer = Answer.new
  end

  # GET /answers/1/edit
  def edit
  end

  # POST /answers
  def create
    @answer = Answer.new(answer_params)

    respond_to do |format|
      if @answer.save
        format.html { redirect_to @answer.question.lesson,
          tr(:answer, 'created') }
        format.js
      else
        format.html
        format.js
      end
    end
  end

  # PATCH/PUT /answers/1
  def update
    if @answer.update(answer_params)
      redirect_to @answer.question.lesson, tr(:answer, 'updated')
    else
      render :edit
    end
  end

  # DELETE /answers/1
  def destroy
    @answer.destroy
    redirect_to @answer.question.lesson, tr(:answer, 'deleted')
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = Answer.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def answer_params
      params.require(:answer).permit(:text, :final,
        answers_attributes: [:id, :text, :correct, :_destroy])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :set_lesson, only: [:show, :edit, :update, :destroy]

  # GET /lessons
  def index
    @lessons = Lesson.all
  end

  # GET /lessons/1
  def show
  end

  # GET /lessons/new
  def new
    @lesson = Lesson.new
    @lesson.images.build
  end

  # GET /lessons/1/edit
  def edit
    @lesson.images.build
  end

  # POST /lessons
  def create
    @lesson = Lesson.new(lesson_params)
    if @lesson.save
      questions_ids = params[:questions]
      Question.where(id: questions_ids).update_all(lesson_id: @lesson.id)
      redirect_to @lesson, notice: 'Урок успешно создан.'
    else
      @lesson.images.build if @lesson.images.empty?
      render :new
    end
  end

  # PATCH/PUT /lessons/1
  def update
    if @lesson.update(lesson_params)
      questions_ids = params[:questions]
      Question.where(id: questions_ids).update_all(lesson_id: @lesson.id)
      redirect_to @lesson, notice: 'Урок успешно отредактирован.'
    else
      render :edit
    end
  end

  # DELETE /lessons/1
  def destroy
    @lesson.destroy
    redirect_to lessons_url, notice: 'Урок успешно удален.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lesson
      @lesson = Lesson.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def lesson_params
      params.require(:lesson).permit(:name, :description, :questions,
        images_attributes: [:id, :file, :_destroy])
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /questions
  def index
    @questions = Question.all
  end

  # GET /questions/1
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, tr(:question, 'created') }
        format.js
      else
        format.html
        format.js
      end
    end
  end

  # PATCH/PUT /questions/1
  def update
    if @question.update(question_params)
      redirect_to @question, tr(:question, 'updated')
    else
      render :edit
    end
  end

  # DELETE /questions/1
  def destroy
    @question.destroy
    redirect_to @question.lesson, tr(:question, 'deleted')
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def question_params
      params.require(:question).permit(:text, :final,
        answers_attributes: [:id, :text, :correct, :_destroy])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(text)
    text.empty? ? 'Modal': text
  end

  def description(text)
    text.empty? ? 'Modal' : text
  end

  def body_class
    "#{controller_name} #{action_name}"
  end

  def tr(model, action, gender='male')
    { notice: tr_raw(model, action, gender) }
  end

  def tr_raw(model, action, gender='male')
    t("model.#{gender}.#{action}",
      model: t("activerecord.models.#{model}", count: 1))
  end

  def lesson_questions
    params[:questions] || []
  end

  def lesson_questions_to_attach
    Question.find(lesson_questions)
  end
end

app/views/layouts/_messages.html.slim
/ Rails flash messages styled for Bootstrap 2.3
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div class="alert alert-#{name.to_s == 'notice' ? "success" : "error"}"
      button.close[type="button" data-dismiss="alert"] ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.slim
/ navigation styled for Bootstrap 2.3
.navbar
  .navbar-inner
    .container
      a.btn.btn-navbar[data-toggle="collapse" data-target=".nav-collapse"]
        span.icon-bar
        span.icon-bar
        span.icon-bar
      .nav-collapse.collapse
        .navbar.navbar-fixed-top
          nav.navbar-inner
            ul.nav
              li
                = link_to 'Уроки', root_path
              li
                = link_to 'Создать урок', new_lesson_path

app/views/layouts/application.html.slim
doctype html
html lang=I18n.locale
  head
    meta charset="UTF-8"
    meta http-equiv="X-UA-Compatible" content="IE=edge"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title= title(yield :title)
    meta name="description" content=description(yield(:description))
    meta name="keywords" content=""
    == stylesheet_link_tag :application, media: 'all'
    == javascript_include_tag :application
    == csrf_meta_tags
  body class=body_class
    / application layout styled for Bootstrap 2.3
    header
      == render 'layouts/navigation'
    main role="main"
      .container
        .content

          .row
            #content.span12
              == render 'layouts/messages'
              == yield
          footer

app/views/lessons/_form.html.slim
- if @lesson.errors.any?
  #error_explanation
    h2 Не получилось сохранить Урок:
    ul.errors
      - @lesson.errors.full_messages.each do |message|
        li = message

= form_for @lesson, html: { multipart: true } do |f|
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_area :description

  .form-group
    h4 Фото
    = f.fields_for :images do |i|
      .file-upload
        - if i.object.persisted?
          = link_to i.object.file.url do
            = image_tag i.object.file.url(:thumb)
          br/
          = i.object.file.name
          br/
          | Удалить
          = i.check_box '_destroy'
        - else
          = i.label :file
          = i.file_field :file

    = link_to "Добавить еще файл", '#', class: "add-file btn btn-info btn-small"

  .form-group
    h4 Вопросы
    ol.questions
      - @lesson.questions.each do |question|
        li= render 'questions/question', question: question

      - lesson_questions_to_attach.each do |associated_question|
        li= render 'questions/question', question: associated_question

    = link_to "Добавить вопрос", "#", "data-target" => '#newQuestionModal', class: "btn add-question", "data-toggle" => "modal"

    - lesson_questions.each do |question_id|
      = hidden_field_tag "questions[]", question_id

  .actions = f.submit "Сохранить урок", class: 'btn btn-success'

= render 'questions/modal', id: 'newQuestionModal', question: @lesson.questions.build

app/views/lessons/edit.html.slim
= content_for :title, "Редактрование урока #{@lesson.id}"

h1 Редактирование урока

== render 'form'

= link_to 'Открыть', @lesson

= link_to lessons_path, class: "btn btn-link" do
  i.icon-arrow-left
  |  Назад

app/views/lessons/index.html.slim
= content_for :title, "Уроки"

h1 Тестовое задание
h3 Заргузка группы файлов в модальном окне

h4 Уроки

table.table.table-striped.table-bordered
  thead
    tr
      th Название
      th Описание
      th Фото
      th

  tbody
    - @lessons.each do |lesson|
      tr
        td = lesson.name
        td = lesson.description
        td.images
          - lesson.images.each do |image|
            = image_tag image.file.url(:mini), class: 'image'
        td
          = link_to 'Показать', lesson, class: 'btn btn-link'
          = link_to 'Редактировать', [:edit, lesson], class: 'btn btn-link'
          = link_to 'Удалить', lesson, data: {confirm: 'Вы уверены?'}, method: :delete, class: 'btn btn-link'

br

= link_to 'Создать урок', new_lesson_path, class: 'btn btn-success'

app/views/lessons/new.html.slim
= content_for :title, "Создать урок"

h1 Новый урок

== render 'form'

= link_to lessons_path, class: "btn btn-link" do
  i.icon-arrow-left
  |  Назад

app/views/lessons/show.html.slim
= content_for :title, "Урок #{@lesson.id}"

h3 Урок #{@lesson.id}

p
  strong Название:
  br/
  = @lesson.name
p
  strong Описание:
  br/
  = @lesson.description

.images
  - @lesson.images.each do |image|
    = image_tag image.file.url(:medium), class: 'image' if image.persisted?

h5 Вопросы
ol.questions
  - @lesson.questions.each do |question|
    li= render 'questions/question', question: question

= link_to lessons_path, class: "btn btn-link" do
  i.icon-arrow-left
  |  Назад

= link_to 'Править', [:edit, @lesson], class: "btn btn-link"

app/views/pages/index.html.slim
= content_for :title, "Домашняя"

h1 Тестовое задание
h2 Заргузка группы файлов в модальном окне

app/views/questions/_form.html.slim
- question.answers.build if question.answers.empty? || question.answers.last.persisted?

- if question.errors.any?
  #error_explanation.question-errors
    h2 Не получилось сохранить вопрос
    ul.errors
      - question.errors.full_messages.each do |message|
        li = message

= form_for question, remote: true do |f|
  .field
    = f.label :text
    = f.text_field :text
    = f.label :final, class: 'checkbox' do
      = f.check_box :final
      = t('activerecord.attributes.question.final')
  .form-group
    h4 Ответы
    table
      = f.fields_for :answers do |a|
        tr.answer
          td.text
            = a.label :text
            = a.text_field :text

          td.correct
            = a.label :correct, class: 'checkbox' do
              = a.check_box :correct
              = t('activerecord.attributes.answer.correct')

          td.delete
            /- delete_link = a.object.persisted? ? a.object : '#'
            - delete_class = a.object.persisted? ? "" : "only-html"
            = link_to '#', data: {confirm: 'Вы уверены?', toggle: "tooltip"}, method: :delete, class: "delete-answer #{delete_class}", title: "Удалить ответ" do
              i.icon-remove

  = link_to "Добавить ответ", '#', class: "add-answer btn btn-info btn-small"

app/views/questions/_modal.html.slim
.modal.hide.fade id=id
  .modal-header
    button.close aria-hidden="true" data-dismiss="modal" type="button" &times;
    h3= question.try(:persisted?) ? "Редактировать вопрос" : "Новый вопрос"
  .modal-body
    = render 'questions/form', question: question
  .modal-footer
    a.btn href="#" data-dismiss="modal" Закрыть
    a.btn.btn-success.submit-form href="#" Сохранить вопрос

app/views/questions/_question.html.slim
.question id="question-#{question.id}"
  p.question-text
    = question.text
    - if question.final?
      span.label.label-info для итогового тестирования
  p.no-margin
    strong Ответы
  ol.answers
    - question.answers.each do |answer|
      li.answer
        = answer.text
        - if answer.correct?
          span.label.label-success правильный

  .actions
    = link_to 'Редактировать', [:edit, question], class: 'btn btn-small'
    = link_to 'Удалить', question, data: {confirm: 'Вы уверены?'}, method: :delete, class: 'btn btn-small btn-danger'

app/views/questions/create.js.erb
<% if @question.errors.empty? %>
  $('.modal').modal('hide');
  $('#content').prepend(
    '<%= j render 'layouts/messages', flash: tr(:question, 'created') %>'
  );
  $('#new_question #question_text').val('');
  $('#new_question #question_answers_attributes_0_text').val('');
  $('#new_question .question-errors').hide();
  $("#new_question .field_with_errors").each(function(){
    $(this).replaceWith($(this).html());
  });

  $('.questions').append(
    '<li> <%= j render 'questions/question', question: @question %> </li>'
  );
  $('.questions .question').last().css('background-color', '#fffff7');

  $('#content > form').append(
    '<%= hidden_field_tag "questions[]", @question.id %> '
  );

<% else %>
  $('#new_question').html(
    '<%= j render 'questions/form', question: @question %>'
  );
<% end %>

app/views/questions/edit.html.slim
h1 Editing question

== render 'form', question: @question

= link_to 'Show', @question
'|
= link_to 'Back', questions_path

app/views/questions/index.html.slim
h1 Listing questions

table.table.table-striped.table-bordered
  thead
    tr
      th Текст
      th Итоговый
      th Ответы
      th

  tbody
    - @questions.each do |question|
      tr
        td= question.text
        td= question.final
        td= question.answers.count
        td
          = link_to 'Show', question
          = link_to 'Edit', edit_question_path(question)
          = link_to 'Destroy', question, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Question', new_question_path

app/views/questions/new.html.slim
h1 New question

== render 'form'

= link_to 'Back', questions_path

app/views/questions/show.html.slim
= link_to 'Edit', edit_question_path(@question)
'|
= link_to 'Back', questions_path